name: Terragrunt Dev Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  terragrunt:
    name: Terragrunt Destroy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::522814728660:role/sivaramakrishna-konka-iam-github-actions
          role-session-name: GitHubActionsTerraform
          aws-region: ap-south-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.5

      - name: Setup Terragrunt
        run: |
          curl -sL https://github.com/gruntwork-io/terragrunt/releases/download/v0.55.1/terragrunt_linux_amd64 -o /usr/local/bin/terragrunt
          chmod +x /usr/local/bin/terragrunt
          terragrunt --version

      - name: Terragrunt Init
        run: terragrunt init
        working-directory: ./live/dev

      - name: Terragrunt Destroy
        run: terragrunt destroy -auto-approve
        working-directory: ./live/dev